# Generated by Django 4.2.5 on 2025-04-25 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='media',
            field=models.FileField(blank=True, help_text='Upload image or PDF file', null=True, upload_to='ticket_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'pdf'])]),
        ),
    ]
