# Generated by Django 5.2.11 on 2026-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('store_admin', 'Store Admin'), ('pos_staff', 'POS Staff')], max_length=20, null=True),
        ),
    ]
