# Generated by Django 4.2.5 on 2024-08-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
