from django.urls import path
from .views import (
    category_list,
    product_list,
    place_order,
    get_special_menu,
    active_coupons,
    get_razorpay_credentials,
    get_outlet_details,
    add_or_update_razorpay_credentials,
    add_or_update_qr_customization,
    create_special_menu,
    update_special_menu_name,
    generate_table_qrs,
    add_colors_to_palette,
    remove_colors_from_palette,
    add_product_to_special_menu,
    remove_product_from_special_menu,
    create_banner,
    delete_banner,
    list_banners,
    get_banner,
    update_banner,
    get_qr_customization,
    toggle_qr_razorpay,
)

urlpatterns = [
    path('get-categories/<int:outlet_id>/', category_list, name='category-list'),
    path('get-products/<int:outlet_id>/', product_list, name='product_list'),
    path('place-order/<int:outlet_id>/', place_order, name='place_order'),
    path('special-menu/<int:outlet_id>/', get_special_menu, name='get_special_menu'),
    path("create-banner/<int:outlet_id>/banners/create/", create_banner, name="create_banner"),
    path("get-banners/<int:outlet_id>/banners/", list_banners, name="list_banners"),
    path("get-specific-banner/<int:banner_id>/", get_banner, name="get_banner"),
    path("update-banner/<int:banner_id>/update/", update_banner, name="update_banner"),
    path("delete-banner/<int:banner_id>/delete/", delete_banner, name="delete_banner"),
    path('get-coupons/<int:outlet_id>/', active_coupons, name='active-coupons'),
    path('razorpay/<int:outlet_id>/', get_razorpay_credentials, name='get_razorpay_credentials'),
    path('razorpay/add/<int:outlet_id>/', add_or_update_razorpay_credentials, name='razorpay-credential'),
    path('get-outlet-details/<int:outlet_id>/', get_outlet_details, name='get_outlet_details'),
    path('qr-customization/add/<int:outlet_id>/', add_or_update_qr_customization, name='qr-customization'),
    path('special-menu/add/<int:outlet_id>/', create_special_menu, name='add-special-menu'),
    path("special-menu-add-product/<int:menu_id>/<int:product_id>/", add_product_to_special_menu, name="add_product_to_special_menu"),
    path("special-menu-remove-product/<int:menu_id>/<int:product_id>/", remove_product_from_special_menu, name="remove_product_from_special_menu"),
    path('special-menu/update-name/<int:outlet_id>/', update_special_menu_name, name='update_special_menu_name'),
    path('generate-qr/<int:outlet_id>/', generate_table_qrs, name='generate_table_qrs'),
    path('qr-customization/colors/<int:outlet_id>/add/',add_colors_to_palette,name='add_colors_to_palette'),
    path('qr-customization/colors/<int:outlet_id>/remove/',remove_colors_from_palette,name='remove_colors_from_palette'),
    path('get-qr-customization/<int:outlet_id>/',get_qr_customization,name='get_qr_customization'),
    path('toggle-razorpay/<int:outlet_id>/', toggle_qr_razorpay, name='toggle_qr_razorpay'),
]