# Generated by Django 5.2.11 on 2026-06-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('v1', '0051_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='linked_variant',
            field=models.ForeignKey(blank=True, help_text='Link to a sellable product variant if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_links', to='v1.productvariant'),
        ),
    ]
