# Generated by Django 4.2.5 on 2024-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
