# Generated by Django 4.2.5 on 2024-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_company_number_of_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plain_password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
