# Generated by Django 4.2.5 on 2024-08-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_company_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='plain_password',
        ),
    ]
