# Generated by Django 5.0.6 on 2024-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_remove_stockrequest_requested_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash Payment'), ('coupon', 'Coupon')], max_length=10, null=True),
        ),
    ]
