# Generated by Django 4.2.5 on 2025-03-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_alter_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_veg',
            field=models.BooleanField(default=True, help_text='Indicates if the item is veg.'),
        ),
    ]
