# Generated by Django 4.2.5 on 2025-04-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply on all categories', to='v1.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max discount in ₹ (only applicable for percentage type)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_cart_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply on all products', to='v1.product'),
        ),
    ]
