# Generated by Django 4.2.5 on 2025-04-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0020_coupon_categories_coupon_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='v1.outlet'),
            preserve_default=False,
        ),
    ]
