# Generated by Django 4.2.5 on 2025-04-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_coupon_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock_out',
            field=models.BooleanField(default=False, help_text='True if the product is out of stock'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_stock_out',
            field=models.BooleanField(default=False, help_text='True if the product is out of stock'),
        ),
    ]
