# Generated by Django 4.2.5 on 2025-05-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0022_product_is_stock_out_productvariant_is_stock_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
