# Generated by Django 4.2.5 on 2025-05-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0023_employee_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_client_id', models.CharField(max_length=100)),
                ('razorpay_client_secret', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_credential', to='v1.outlet')),
            ],
        ),
    ]
