# Generated by Django 4.2.5 on 2025-05-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0025_fcmtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fcmtokens', to='v1.outlet'),
            preserve_default=False,
        ),
    ]
