# Generated by Django 4.2.5 on 2025-05-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0026_remove_fcmtoken_user_fcmtoken_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='v1.employee')),
            ],
        ),
    ]
