# Generated by Django 4.2.5 on 2025-05-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0027_employeecredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecredentials',
            name='username',
        ),
        migrations.AddField(
            model_name='employeecredentials',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
