# Generated by Django 4.2.5 on 2025-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_remove_employeecredentials_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, help_text='Table number if dine-in, else leave empty.', null=True),
        ),
    ]
