# Generated by Django 4.2.5 on 2025-06-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0029_order_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_title', models.CharField(max_length=255)),
                ('refund_description', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_notes', to='v1.order')),
            ],
        ),
    ]
