# Generated by Django 4.2.5 on 2025-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0031_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Any specific note or instruction for the order.', null=True),
        ),
    ]
