# Generated by Django 4.2.5 on 2025-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0032_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter GST percentage.', max_digits=5, null=True),
        ),
    ]
