# Generated by Django 4.2.5 on 2025-11-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0033_alter_product_gst_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printers', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_config', to='v1.outlet')),
            ],
        ),
    ]
