# Generated by Django 5.2.11 on 2026-03-31 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0034_printerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('rejected', 'Rejected'), ('ready_to_serve', 'Ready to Serve')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('payment_pending', 'Payment Pending'), ('settled', 'Settled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('table_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(help_text='Eg: Ground Floor, First Floor', max_length=50)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('running', 'Running'), ('printing', 'Printing'), ('paid', 'Paid'), ('running_kot', 'Running KOT')], default='empty', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_current_orders', to='v1.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='v1.outlet')),
            ],
        ),
    ]
