# Generated by Django 5.2.11 on 2026-03-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0036_remove_order_table_number_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='table_number',
        ),
    ]
