# Generated by Django 5.2.11 on 2026-04-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0038_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='KOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kot_number', models.PositiveIntegerField()),
                ('items', models.JSONField(help_text='[{product_id, product_name, quantity}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='v1.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='v1.table')),
            ],
        ),
    ]
