# Generated by Django 5.2.11 on 2026-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0040_table_created_at_kotdevice_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_transaction_id',
            field=models.CharField(blank=True, help_text='Original transaction ID for refund/void', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pine_payment_mode',
            field=models.CharField(blank=True, help_text='Final payment mode (UPI/Card/etc)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pine_response',
            field=models.JSONField(blank=True, help_text='Full PineLabs response for audit/debug', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pine_transaction_number',
            field=models.CharField(blank=True, help_text='Same as TransactionNumber sent to PineLabs', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='plutus_transaction_reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='PTRN returned by PineLabs', max_length=100, null=True),
        ),
    ]
