# Generated by Django 5.2.11 on 2026-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0042_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotdevice',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_kot',
            field=models.BooleanField(default=False),
        ),
    ]
