# Generated by Django 5.2.11 on 2026-04-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0043_kotdevice_is_logged_in_plan_has_kot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('settled', 'Settled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
