# Generated by Django 5.2.11 on 2026-04-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0045_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotdevice',
            name='outlet',
        ),
        migrations.AddField(
            model_name='kotdevice',
            name='outlet_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
