# Generated by Django 5.2.11 on 2026-04-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0046_remove_kotdevice_outlet_kotdevice_outlet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotdevice',
            name='outlet_id',
        ),
    ]
