# Generated by Django 5.2.11 on 2026-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0047_remove_kotdevice_outlet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_type',
            field=models.CharField(blank=True, help_text='UPI provider like gpay, phonepe, paytm', max_length=20, null=True),
        ),
    ]
