# Generated by Django 5.2.11 on 2026-04-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0048_order_upi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('running', 'Running'), ('printing', 'Printing'), ('paid', 'Paid'), ('running_kot', 'Running KOT'), ('pending_counter_confirmation', 'Pending Counter Confirmation')], default='empty', max_length=50),
        ),
    ]
