# Generated by Django 5.2.11 on 2026-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0050_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('settled', 'Settled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('pending_confirmation', 'Pending Confirmation')], default='pending', max_length=40),
        ),
    ]
