# Generated by Django 5.2.11 on 2026-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0051_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
