# Generated by Django 5.2.11 on 2026-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0052_plan_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gst_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
