# Generated by Django 5.2.11 on 2026-06-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0054_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(choices=[('pine_labs', 'Pine Labs Integration'), ('kot', 'Kitchen Order Ticket (KOT)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='kot',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='v1.order'),
        ),
        migrations.AlterField(
            model_name='kot',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='v1.table'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_mode',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash'), ('card', 'Card'), ('coupon', 'Coupon'), ('pine_labs_card', 'Pine Labs Card')], max_length=20),
        ),
        migrations.DeleteModel(
            name='FCMToken',
        ),
    ]
