# Generated by Django 5.2.11 on 2026-06-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0055_alter_addon_name_alter_kot_order_alter_kot_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecredentials',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeecredentials',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
