# Generated by Django 4.2.5 on 2025-05-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1', '0024_razorpaycredential'),
        ('qr', '0009_remove_order_outlet_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_logo', models.ImageField(blank=True, null=True, upload_to='qr_logos/')),
                ('theme_color', models.CharField(blank=True, max_length=7, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_customization', to='v1.outlet')),
            ],
        ),
    ]
