# Generated by Django 4.2.5 on 2025-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcustomization',
            name='color_palette',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
