# Generated by Django 4.2.5 on 2025-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_remove_employeecredentials_username_and_more'),
        ('qr', '0011_qrcustomization_color_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Special Menu', max_length=255)),
                ('products', models.ManyToManyField(related_name='special_menus', to='v1.product')),
            ],
        ),
    ]
