# Generated by Django 4.2.5 on 2025-05-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_remove_employeecredentials_username_and_more'),
        ('qr', '0012_specialmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL of the banner image.')),
                ('redirect_url', models.URLField(help_text='URL to redirect when the banner is clicked.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_banners', to='v1.outlet')),
            ],
        ),
    ]
