# Generated by Django 4.2.5 on 2025-05-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_remove_employeecredentials_username_and_more'),
        ('qr', '0013_advertisementbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmenu',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='special_menus', to='v1.outlet'),
            preserve_default=False,
        ),
    ]
