# Generated by Django 4.2.5 on 2025-05-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0029_order_table_number'),
        ('qr', '0014_specialmenu_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletTableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tables', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_config', to='v1.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='TableQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_qrs', to='v1.outlet')),
            ],
            options={
                'unique_together': {('outlet', 'table_number')},
            },
        ),
    ]
