# Generated by Django 5.2.11 on 2026-06-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0015_outlettableconfiguration_tableqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcustomization',
            name='is_razorpay_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
