# Generated by Django 4.2.5 on 2024-08-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdetails',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
